name: Deploy GCP

on:
  push:
    branches: [ main ]
jobs:
  build-and-push-to-gcr-waterloo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        env:
          ENV_WATERLOO: ${{ secrets.ENV_WATERLOO }}
        run: |
          echo $ENV_WATERLOO | base64 --decode > .env
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: mentor-pilot-project
          image_name: test-deploy
          image_tag: latest,waterloo,${{github.sha}}

  build-and-push-to-gcr-purdue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        env:
          ENV_PURDUE: ${{ secrets.ENV_PURDUE }}
        run: |
          echo $ENV_PURDUE | base64 --decode > .env
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: mentor-pilot-project
          image_name: test-deploy
          image_tag: latest,purdue,${{github.sha}}