name: Deploy GCP

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: mentor-pilot-project
  GKE_CLUSTER: gke-1mentor-cluster-1
  GKE_ZONE: us-central1-c
  IMAGE: test-deploy
  PURDUE_VARIABLES: ${{ secrets.ENV_PURDUE }}
  B2C_VARIABLES: ${{ secrets.ENV_B2C }}

jobs:
  build-and-push-to-gcr-purdue:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ env.PROJECT_ID }}
      - run: |-
          gcloud --quiet auth configure-docker

      - uses: actions/checkout@v3
      - name: Build
        run: |-
          echo "$PURDUE_VARIABLES" | base64 -d > .env
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE/purdue:latest" $(for i in `cat .env`; do out+="--build-arg $i " ; done; echo $out;out="") .

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE/purdue:latest"  

  build-and-push-to-gcr-b2c:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ env.PROJECT_ID }}
      - run: |-
          gcloud --quiet auth configure-docker

      - uses: actions/checkout@v3
      - name: Build
        run: |-
          echo "$B2C_VARIABLES" | base64 -d > .env
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE/b2c:latest" $(for i in `cat .env`; do out+="--build-arg $i " ; done; echo $out;out="") .

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE/b2c:latest"